# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Uptown Stories
email: kate@uptownstories.org
description: > # this means to ignore newlines until "baseurl:"
  At Uptown Stories, we believe that writing is an essential tool for self-expression, critical thinking, and academic success.Based in upper Manhattan, we offer small-group writing workshops for children ages eight to fifteen, led by master teachers and professional authors.  To ensure our workshops are accessible to all children, tuition is pay-what-you-can.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://uptownstories.github.io" # the base hostname & protocol for your site
twitter_username: uptownstories
github_username:  uptownstories

# Build settings
markdown: kramdown
kramdown:
  input: GFM

collections:
  classes:
    output: false
